### ISSUE TITLE
PostgreSQL Spring boot configuration

### ISSUE THREAD

**Issue by MamaboloGtub** [MamaboloGtub/spring-jpa-intro#25]

**Comment by Vijay-948** [comment]
can you assign me this?

**Comment by MamaboloGtub** [comment]
> can you assign me this?

Hi  @Vijay-948 Thanks for showing interest,  but unfortunately this project is part of a udemy course which I have registered and it  is also for my work upskilling,  so I have to follow each issue to see if I have understood any work and lectures.  So I have to do everything step by step on my own.
